.TH "SUDOKU-TK" "1" "October 2018" "sudoku-tk 1.2.0" ""
.SH NAME
Sudoku-Tk \- Sudoku games and puzzle solver
.SH SYNOPSIS
.B sudoku-tk
.RI [file_name]
.SH DESCRIPTION
Sudoku-Tk enables you to play sudoku. You can load puzzles, generate 
puzzles or start from an empty grid. Sudoku-Tk can also solve the sudoku.
.SH OPTIONS
.TP
.B file_name
Optional. The name of the file (.sudoku or .txt puzzle) to open.
.SH AUTHOR
Sudoku-Tk is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Github page of the project
\fBhttps://github.com/j4321/Sudoku-Tk/issues\fR 
or send an email to <j_4321@protonmail.com>.
